name: yoctobuild

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bitbake
      run: |
        git submodule update --init --recursive
        sudo apt -y update && sudo apt -y install \
          gawk \
          wget \
          git \
          diffstat \
          unzip \
          texinfo \
          gcc \
          build-essential \
          chrpath \
          socat \
          cpio \
          python3 \
          python3-pip \
          python3-pexpect \
          xz-utils \
          debianutils \
          iputils-ping \
          python3-git \
          python3-jinja2 \
          libegl1-mesa \
          libsdl1.2-dev \
          pylint3 \
          xterm \
          python3-subunit \
          mesa-common-dev \
          zstd \
          liblz4-tool
        
        pwd
        echo ${GITHUB_WORKSPACE} 
        . ${GITHUB_WORKSPACE}/poky/oe-init-build-env

        cat build/conf/local.conf | grep BB_SIGNATURE_HANDLER
        bitbake core-image-minimal
        bitbake core-image-minimal - g

        pushd ${GITHUB_WORKSPACE}/export_bitbake_dot_depends && ./export_depends_dot.sh && popd || popd
        pushd ${GITHUB_WORKSPACE}/export_bitbake_dot_depends && python3 -m dot2graph && popd || popd
